import type { BattleIntensity, EnemyDifficulty } from "./types.js";

export type MonsterAbilityScores = {
  strength: number;
  agility: number;
  constitution: number;
  mind: number;
  wisdom: number;
  presence: number;
};

export type MonsterAction = {
  name: string;
  attackBonus: number;
  damageDie: "d4" | "d6" | "d8" | "d10" | "d12";
  damageDiceCount: number;
  damageModifier: number;
  damageType: string;
  reach?: string;
  range?: string;
  notes?: string;
};

export type MonsterStatBlock = {
  id: string;
  name: string;
  kind: "humanoid" | "beast" | "undead" | "giant" | "monstrosity" | "elemental" | "construct" | "fiend";
  size: "small" | "medium" | "large";
  family?: string;
  role?: "minion" | "skirmisher" | "brute" | "controller" | "lurker" | "soldier" | "leader" | "artillery";
  biomeTags?: string[];
  challengeRating: string;
  xpValue: number;
  armorClass: number;
  hitPoints: number;
  speed: string;
  abilities: MonsterAbilityScores;
  senses?: string;
  languages?: string;
  traits: string[];
  actions: MonsterAction[];
  description: string;
  suggestedLevels: number[];
  difficultyBand: EnemyDifficulty[];
};

export type EncounterMonster = MonsterStatBlock & {
  name: string;
  hitPoints: number;
  xpValue: number;
  threat: number;
};

const coreMonsterCatalog: MonsterStatBlock[] = [
  {
    id: "cultist",
    name: "Cultista",
    kind: "humanoid",
    size: "medium",
    family: "cult",
    role: "minion",
    biomeTags: ["templo", "cripta", "cidade", "ruina", "taverna"],
    challengeRating: "1/8",
    xpValue: 25,
    armorClass: 12,
    hitPoints: 9,
    speed: "9m",
    abilities: { strength: 11, agility: 12, constitution: 10, mind: 10, wisdom: 11, presence: 10 },
    languages: "Comum",
    traits: ["Fanatismo: luta por medo, promessa ou devoção, mas costuma quebrar moral se isolado."],
    actions: [{ name: "Cimitarra", attackBonus: 3, damageDie: "d6", damageDiceCount: 1, damageModifier: 1, damageType: "cortante", reach: "1,5m" }],
    description: "Um humanoide fanático com arma simples e convicção perigosa, mais útil como pista viva do que como grande ameaça.",
    suggestedLevels: [1],
    difficultyBand: ["story"],
  },
  {
    id: "bandit",
    name: "Bandido",
    kind: "humanoid",
    size: "medium",
    family: "criminal",
    role: "skirmisher",
    biomeTags: ["cidade", "estrada", "taverna", "porto", "floresta"],
    challengeRating: "1/8",
    xpValue: 25,
    armorClass: 12,
    hitPoints: 11,
    speed: "9m",
    abilities: { strength: 11, agility: 12, constitution: 12, mind: 10, wisdom: 10, presence: 10 },
    languages: "Comum",
    traits: ["Covardia prática: prefere emboscada, vantagem numérica e fuga se a luta virar."],
    actions: [{ name: "Espada curta", attackBonus: 3, damageDie: "d6", damageDiceCount: 1, damageModifier: 1, damageType: "perfurante", reach: "1,5m" }],
    description: "Um criminoso armado, perigoso em grupo e raramente disposto a morrer por uma causa.",
    suggestedLevels: [1],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "goblin",
    name: "Goblin",
    kind: "humanoid",
    size: "small",
    family: "goblinoid",
    role: "skirmisher",
    biomeTags: ["floresta", "caverna", "ruina", "estrada", "pantano"],
    challengeRating: "1/4",
    xpValue: 50,
    armorClass: 15,
    hitPoints: 7,
    speed: "9m",
    abilities: { strength: 8, agility: 14, constitution: 10, mind: 10, wisdom: 8, presence: 8 },
    senses: "visão no escuro",
    languages: "Comum, Goblin",
    traits: ["Escape ágil: pode se esconder ou recuar rapidamente quando pressionado."],
    actions: [{ name: "Cimitarra", attackBonus: 4, damageDie: "d6", damageDiceCount: 1, damageModifier: 2, damageType: "cortante", reach: "1,5m" }],
    description: "Pequeno, cruel e oportunista; prefere terreno ruim, armadilhas e ataques quando o alvo está distraído.",
    suggestedLevels: [1, 2],
    difficultyBand: ["standard"],
  },
  {
    id: "skeleton",
    name: "Esqueleto",
    kind: "undead",
    size: "medium",
    family: "skeleton",
    role: "soldier",
    biomeTags: ["cripta", "cemiterio", "templo", "ruina", "masmorra"],
    challengeRating: "1/4",
    xpValue: 50,
    armorClass: 13,
    hitPoints: 13,
    speed: "9m",
    abilities: { strength: 10, agility: 14, constitution: 15, mind: 6, wisdom: 8, presence: 5 },
    senses: "visão no escuro",
    languages: "entende idiomas que conhecia em vida",
    traits: ["Morto-vivo: não sente medo comum e ignora apelos sociais simples."],
    actions: [{ name: "Espada curta", attackBonus: 4, damageDie: "d6", damageDiceCount: 1, damageModifier: 2, damageType: "perfurante", reach: "1,5m" }],
    description: "Ossos animados por magia ou maldição, obedientes e silenciosos até serem destruídos.",
    suggestedLevels: [1, 2],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "wolf",
    name: "Lobo",
    kind: "beast",
    size: "medium",
    family: "wolf",
    role: "skirmisher",
    biomeTags: ["floresta", "estrada", "montanha", "fronteira", "acampamento"],
    challengeRating: "1/4",
    xpValue: 50,
    armorClass: 13,
    hitPoints: 11,
    speed: "12m",
    abilities: { strength: 12, agility: 15, constitution: 12, mind: 3, wisdom: 12, presence: 6 },
    senses: "olfato e audição aguçados",
    traits: ["Tática de matilha: fica mais perigoso quando outro aliado ameaça o mesmo alvo."],
    actions: [{ name: "Mordida", attackBonus: 4, damageDie: "d4", damageDiceCount: 2, damageModifier: 2, damageType: "perfurante", reach: "1,5m", notes: "Pode derrubar se o alvo falhar em resistir." }],
    description: "Predador de matilha que testa fraqueza antes de se comprometer com a presa.",
    suggestedLevels: [1, 2],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "orc",
    name: "Orc",
    kind: "humanoid",
    size: "medium",
    family: "orc",
    role: "brute",
    biomeTags: ["estrada", "fronteira", "acampamento", "floresta", "montanha"],
    challengeRating: "1/2",
    xpValue: 100,
    armorClass: 13,
    hitPoints: 15,
    speed: "9m",
    abilities: { strength: 16, agility: 12, constitution: 16, mind: 7, wisdom: 11, presence: 10 },
    senses: "visão no escuro",
    languages: "Comum, Orc",
    traits: ["Agressivo: avança para fechar distância e forçar combate corpo a corpo."],
    actions: [{ name: "Machado grande", attackBonus: 5, damageDie: "d12", damageDiceCount: 1, damageModifier: 3, damageType: "cortante", reach: "1,5m" }],
    description: "Guerreiro brutal e direto, perigoso quando consegue manter pressão sem ser controlado.",
    suggestedLevels: [1, 2],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "ghoul",
    name: "Carniçal",
    kind: "undead",
    size: "medium",
    family: "ghoul",
    role: "lurker",
    biomeTags: ["cripta", "cemiterio", "ruina", "templo", "esgoto"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 12,
    hitPoints: 22,
    speed: "9m",
    abilities: { strength: 13, agility: 15, constitution: 10, mind: 7, wisdom: 10, presence: 6 },
    senses: "visão no escuro",
    languages: "Comum",
    traits: ["Garras paralisantes: um golpe limpo pode travar o corpo da vítima por instantes."],
    actions: [{ name: "Garras", attackBonus: 4, damageDie: "d6", damageDiceCount: 2, damageModifier: 2, damageType: "cortante", reach: "1,5m", notes: "Pode impor condição temporária se a mesa pedir teste." }],
    description: "Morto-vivo faminto e veloz, perigoso por controlar movimento e espalhar pânico.",
    suggestedLevels: [2, 3],
    difficultyBand: ["deadly"],
  },
  {
    id: "dire-wolf",
    name: "Lobo Atroz",
    kind: "beast",
    size: "large",
    family: "wolf",
    role: "brute",
    biomeTags: ["floresta", "estrada", "montanha", "fronteira", "caverna"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 14,
    hitPoints: 37,
    speed: "15m",
    abilities: { strength: 17, agility: 15, constitution: 15, mind: 3, wisdom: 12, presence: 7 },
    senses: "olfato e audição aguçados",
    traits: ["Tática de matilha: busca derrubar o alvo para que aliados ataquem com vantagem narrativa."],
    actions: [{ name: "Mordida", attackBonus: 5, damageDie: "d6", damageDiceCount: 2, damageModifier: 3, damageType: "perfurante", reach: "1,5m", notes: "Pode derrubar em falha de resistência." }],
    description: "Predador enorme, inteligente o bastante para cercar, derrubar e separar vítimas.",
    suggestedLevels: [3, 4],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "bugbear",
    name: "Bugbear",
    kind: "humanoid",
    size: "medium",
    family: "goblinoid",
    role: "lurker",
    biomeTags: ["floresta", "caverna", "ruina", "estrada", "acampamento"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 16,
    hitPoints: 27,
    speed: "9m",
    abilities: { strength: 15, agility: 14, constitution: 13, mind: 8, wisdom: 11, presence: 9 },
    senses: "visão no escuro",
    languages: "Comum, Goblin",
    traits: ["Ataque surpresa: causa dano extra quando pega o alvo despreparado."],
    actions: [{ name: "Maça pesada", attackBonus: 4, damageDie: "d8", damageDiceCount: 2, damageModifier: 2, damageType: "concussão", reach: "1,5m" }],
    description: "Caçador sorrateiro e forte, misturando emboscada com pancadas pesadas.",
    suggestedLevels: [3, 4],
    difficultyBand: ["standard"],
  },
  {
    id: "ogre",
    name: "Ogro",
    kind: "giant",
    size: "large",
    family: "giant",
    role: "brute",
    biomeTags: ["montanha", "caverna", "fronteira", "floresta", "ruina"],
    challengeRating: "2",
    xpValue: 450,
    armorClass: 11,
    hitPoints: 59,
    speed: "12m",
    abilities: { strength: 19, agility: 8, constitution: 16, mind: 5, wisdom: 7, presence: 7 },
    languages: "Comum, Gigante",
    traits: ["Força esmagadora: golpes simples, lentos e devastadores contra quem fica ao alcance."],
    actions: [{ name: "Clava grande", attackBonus: 6, damageDie: "d8", damageDiceCount: 2, damageModifier: 4, damageType: "concussão", reach: "1,5m" }],
    description: "Gigante brutal de entendimento limitado, mas capaz de destruir cobertura e punir erro de posição.",
    suggestedLevels: [3, 4, 5],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "young-troll",
    name: "Troll Jovem",
    kind: "giant",
    size: "large",
    family: "troll",
    role: "brute",
    biomeTags: ["pantano", "floresta", "caverna", "ponte", "ruina"],
    challengeRating: "3",
    xpValue: 700,
    armorClass: 15,
    hitPoints: 72,
    speed: "9m",
    abilities: { strength: 18, agility: 13, constitution: 20, mind: 7, wisdom: 9, presence: 7 },
    senses: "olfato aguçado",
    languages: "Gigante",
    traits: ["Regeneração: recupera vigor se fogo ou ácido não impedirem a cura.", "Fome implacável: pressiona alvos feridos."],
    actions: [{ name: "Garras", attackBonus: 7, damageDie: "d6", damageDiceCount: 2, damageModifier: 4, damageType: "cortante", reach: "1,5m" }],
    description: "Troll ainda jovem, menor que um adulto lendário, mas já assustador por se recompor durante a luta.",
    suggestedLevels: [4, 5],
    difficultyBand: ["deadly", "standard"],
  },
  {
    id: "minor-elemental",
    name: "Elemental Menor",
    kind: "elemental",
    size: "medium",
    family: "elemental",
    role: "brute",
    biomeTags: ["ruina", "templo", "caverna", "montanha", "deserto"],
    challengeRating: "4",
    xpValue: 1100,
    armorClass: 14,
    hitPoints: 82,
    speed: "9m",
    abilities: { strength: 16, agility: 14, constitution: 16, mind: 6, wisdom: 10, presence: 8 },
    senses: "sentidos elementais",
    languages: "Primordial",
    traits: ["Corpo elemental: ignora muitas limitações físicas comuns.", "Instabilidade: reage violentamente a dano oposto ao seu elemento."],
    actions: [{ name: "Golpe elemental", attackBonus: 6, damageDie: "d8", damageDiceCount: 2, damageModifier: 3, damageType: "elemental", reach: "1,5m" }],
    description: "Manifestação elemental instável, adequada como ameaça rara e claramente sobrenatural.",
    suggestedLevels: [5],
    difficultyBand: ["deadly"],
  },
];

const expandedMonsterCatalog: MonsterStatBlock[] = [
  {
    id: "commoner",
    name: "Campones Armado",
    kind: "humanoid",
    size: "medium",
    family: "civilian",
    role: "minion",
    biomeTags: ["aldeia", "cidade", "estrada", "fazenda", "taverna"],
    challengeRating: "0",
    xpValue: 10,
    armorClass: 10,
    hitPoints: 4,
    speed: "9m",
    abilities: { strength: 10, agility: 10, constitution: 10, mind: 10, wisdom: 10, presence: 10 },
    languages: "Comum",
    traits: ["Moral fragil: foge se sofrer dano serio ou se vir morte proxima."],
    actions: [{ name: "Porrete", attackBonus: 2, damageDie: "d4", damageDiceCount: 1, damageModifier: 0, damageType: "concussao", reach: "1,5m" }],
    description: "Pessoa comum empurrada ao conflito, ameaca apenas em multidao ou em situacao desesperada.",
    suggestedLevels: [1],
    difficultyBand: ["story"],
  },
  {
    id: "guard",
    name: "Guarda",
    kind: "humanoid",
    size: "medium",
    family: "guard",
    role: "soldier",
    biomeTags: ["cidade", "vila", "forte", "estrada", "taverna", "guilda"],
    challengeRating: "1/8",
    xpValue: 25,
    armorClass: 16,
    hitPoints: 11,
    speed: "9m",
    abilities: { strength: 13, agility: 12, constitution: 12, mind: 10, wisdom: 11, presence: 10 },
    languages: "Comum",
    traits: ["Disciplina: protege civis e tenta prender antes de matar quando possivel."],
    actions: [{ name: "Lanca", attackBonus: 3, damageDie: "d6", damageDiceCount: 1, damageModifier: 1, damageType: "perfurante", reach: "1,5m" }],
    description: "Combatente treinado de patrulha, bom para conflitos urbanos, fronteira e escoltas.",
    suggestedLevels: [1, 2],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "kobold",
    name: "Kobold",
    kind: "humanoid",
    size: "small",
    family: "kobold",
    role: "skirmisher",
    biomeTags: ["caverna", "mina", "ruina", "esgoto", "montanha"],
    challengeRating: "1/8",
    xpValue: 25,
    armorClass: 12,
    hitPoints: 5,
    speed: "9m",
    abilities: { strength: 7, agility: 15, constitution: 9, mind: 8, wisdom: 7, presence: 8 },
    senses: "visao no escuro",
    languages: "Comum, Draconico",
    traits: ["Tatica de bando: evita duelo justo e busca vantagem numerica, armadilhas e corredores estreitos."],
    actions: [{ name: "Adaga", attackBonus: 4, damageDie: "d4", damageDiceCount: 1, damageModifier: 2, damageType: "perfurante", reach: "1,5m" }],
    description: "Pequeno reptiliano covarde sozinho, perigoso quando luta em ninho preparado.",
    suggestedLevels: [1],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "giant-rat",
    name: "Rato Gigante",
    kind: "beast",
    size: "small",
    family: "rat",
    role: "minion",
    biomeTags: ["esgoto", "cripta", "caverna", "cidade", "porão"],
    challengeRating: "1/8",
    xpValue: 25,
    armorClass: 12,
    hitPoints: 7,
    speed: "9m",
    abilities: { strength: 7, agility: 15, constitution: 11, mind: 2, wisdom: 10, presence: 4 },
    senses: "olfato aguçado",
    traits: ["Enxame oportunista: ataca alvos caidos, isolados ou feridos."],
    actions: [{ name: "Mordida", attackBonus: 4, damageDie: "d4", damageDiceCount: 1, damageModifier: 2, damageType: "perfurante", reach: "1,5m" }],
    description: "Praga agressiva de ambientes sujos e subterraneos, mais ameacadora em grupo.",
    suggestedLevels: [1],
    difficultyBand: ["story"],
  },
  {
    id: "giant-spider",
    name: "Aranha Gigante",
    kind: "beast",
    size: "large",
    family: "spider",
    role: "lurker",
    biomeTags: ["floresta", "caverna", "ruina", "pantano"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 14,
    hitPoints: 26,
    speed: "9m, escalar 9m",
    abilities: { strength: 14, agility: 16, constitution: 12, mind: 2, wisdom: 11, presence: 4 },
    senses: "visao no escuro, sentido aracnideo",
    traits: ["Teia: tenta prender antes de morder.", "Predador vertical: usa paredes e teto para surpreender."],
    actions: [{ name: "Mordida venenosa", attackBonus: 5, damageDie: "d8", damageDiceCount: 1, damageModifier: 3, damageType: "perfurante", reach: "1,5m", notes: "Veneno narrativo pode exigir teste se a mesa pedir." }],
    description: "Predador de emboscada que transforma terreno em armadilha viva.",
    suggestedLevels: [2, 3],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "zombie",
    name: "Zumbi",
    kind: "undead",
    size: "medium",
    family: "zombie",
    role: "brute",
    biomeTags: ["cripta", "cemiterio", "ruina", "vila", "pântano", "pantano"],
    challengeRating: "1/4",
    xpValue: 50,
    armorClass: 8,
    hitPoints: 22,
    speed: "6m",
    abilities: { strength: 13, agility: 6, constitution: 16, mind: 3, wisdom: 6, presence: 5 },
    senses: "visao no escuro",
    traits: ["Resistencia morta-viva: pode continuar se movendo apos ferimentos que derrubariam vivos."],
    actions: [{ name: "Pancada", attackBonus: 3, damageDie: "d6", damageDiceCount: 1, damageModifier: 1, damageType: "concussao", reach: "1,5m" }],
    description: "Cadaver animado, lento e resistente, excelente para horror e desgaste.",
    suggestedLevels: [1, 2],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "shadow",
    name: "Sombra",
    kind: "undead",
    size: "medium",
    family: "shadow",
    role: "lurker",
    biomeTags: ["cripta", "templo", "ruina", "masmorra", "floresta"],
    challengeRating: "1/2",
    xpValue: 100,
    armorClass: 12,
    hitPoints: 16,
    speed: "12m",
    abilities: { strength: 6, agility: 14, constitution: 13, mind: 6, wisdom: 10, presence: 8 },
    senses: "visao no escuro",
    traits: ["Forma sombria: evita luz forte e surge de cantos escuros.", "Drenar vigor: ataques podem deixar a vitima fraca."],
    actions: [{ name: "Toque sombrio", attackBonus: 4, damageDie: "d6", damageDiceCount: 2, damageModifier: 2, damageType: "necrotico", reach: "1,5m" }],
    description: "Morto-vivo furtivo e sobrenatural, bom para cenas de terror e consequencias de magia sombria.",
    suggestedLevels: [2, 3],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "swarm-ravens",
    name: "Enxame de Corvos",
    kind: "beast",
    size: "medium",
    family: "swarm",
    role: "controller",
    biomeTags: ["floresta", "cemiterio", "estrada", "ruina", "pântano", "pantano"],
    challengeRating: "1/4",
    xpValue: 50,
    armorClass: 12,
    hitPoints: 24,
    speed: "3m, voo 15m",
    abilities: { strength: 6, agility: 14, constitution: 10, mind: 3, wisdom: 12, presence: 6 },
    senses: "percepcao aguçada",
    traits: ["Enxame: ocupa espaco, distrai e dificulta mira precisa."],
    actions: [{ name: "Bicadas", attackBonus: 4, damageDie: "d6", damageDiceCount: 2, damageModifier: 0, damageType: "perfurante", reach: "0m" }],
    description: "Aves agressivas em massa, boas para mau pressagio, distração e terreno caotico.",
    suggestedLevels: [1, 2],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "thug",
    name: "Capanga",
    kind: "humanoid",
    size: "medium",
    family: "criminal",
    role: "brute",
    biomeTags: ["cidade", "taverna", "estrada", "guilda", "porto"],
    challengeRating: "1/2",
    xpValue: 100,
    armorClass: 11,
    hitPoints: 32,
    speed: "9m",
    abilities: { strength: 15, agility: 11, constitution: 14, mind: 10, wisdom: 10, presence: 11 },
    languages: "Comum",
    traits: ["Brigão de grupo: pressiona quando tem aliados por perto."],
    actions: [{ name: "Maça", attackBonus: 4, damageDie: "d6", damageDiceCount: 1, damageModifier: 2, damageType: "concussao", reach: "1,5m" }],
    description: "Musculo criminoso, util para conflitos de rua, cobrancas e intimidacao.",
    suggestedLevels: [1, 2],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "scout",
    name: "Batedor",
    kind: "humanoid",
    size: "medium",
    family: "scout",
    role: "artillery",
    biomeTags: ["floresta", "estrada", "fronteira", "montanha", "acampamento"],
    challengeRating: "1/2",
    xpValue: 100,
    armorClass: 13,
    hitPoints: 16,
    speed: "9m",
    abilities: { strength: 11, agility: 14, constitution: 12, mind: 11, wisdom: 13, presence: 11 },
    languages: "Comum",
    traits: ["Mobilidade: evita ficar preso em corpo a corpo.", "Rastreador: usa cobertura e informacao do terreno."],
    actions: [{ name: "Arco longo", attackBonus: 4, damageDie: "d8", damageDiceCount: 1, damageModifier: 2, damageType: "perfurante", range: "45/180m" }],
    description: "Arqueiro e rastreador de patrulha, bom para emboscadas e perseguicoes.",
    suggestedLevels: [1, 2],
    difficultyBand: ["standard"],
  },
  {
    id: "acolyte",
    name: "Acolito",
    kind: "humanoid",
    size: "medium",
    family: "priest",
    role: "controller",
    biomeTags: ["templo", "igreja", "cidade", "cripta", "santuario"],
    challengeRating: "1/4",
    xpValue: 50,
    armorClass: 10,
    hitPoints: 9,
    speed: "9m",
    abilities: { strength: 10, agility: 10, constitution: 10, mind: 10, wisdom: 14, presence: 11 },
    languages: "Comum",
    traits: ["Conjurador menor: pode abencoar, curar ou assustar conforme sua fe."],
    actions: [{ name: "Clava", attackBonus: 2, damageDie: "d4", damageDiceCount: 1, damageModifier: 0, damageType: "concussao", reach: "1,5m" }],
    description: "Servo religioso ou cultual com pouca resistencia fisica, mas valor narrativo alto.",
    suggestedLevels: [1, 2],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "gnoll",
    name: "Gnoll",
    kind: "humanoid",
    size: "medium",
    family: "gnoll",
    role: "brute",
    biomeTags: ["estrada", "deserto", "planicie", "ruina", "fronteira"],
    challengeRating: "1/2",
    xpValue: 100,
    armorClass: 15,
    hitPoints: 22,
    speed: "9m",
    abilities: { strength: 14, agility: 12, constitution: 11, mind: 6, wisdom: 10, presence: 7 },
    senses: "visao no escuro",
    languages: "Gnoll",
    traits: ["Frenesi: fica mais perigoso quando sente sangue e fraqueza."],
    actions: [{ name: "Lança", attackBonus: 4, damageDie: "d8", damageDiceCount: 1, damageModifier: 2, damageType: "perfurante", reach: "1,5m" }],
    description: "Saqueador hiena humanoide, violento e caotico, ideal para estradas perigosas.",
    suggestedLevels: [2, 3],
    difficultyBand: ["standard"],
  },
  {
    id: "hobgoblin",
    name: "Hobgoblin",
    kind: "humanoid",
    size: "medium",
    family: "goblin",
    role: "soldier",
    biomeTags: ["forte", "ruina", "estrada", "guerra", "acampamento"],
    challengeRating: "1/2",
    xpValue: 100,
    armorClass: 18,
    hitPoints: 11,
    speed: "9m",
    abilities: { strength: 13, agility: 12, constitution: 12, mind: 10, wisdom: 10, presence: 9 },
    senses: "visao no escuro",
    languages: "Comum, Goblin",
    traits: ["Disciplina marcial: luta melhor em formacao e com aliados."],
    actions: [{ name: "Espada longa", attackBonus: 3, damageDie: "d8", damageDiceCount: 1, damageModifier: 1, damageType: "cortante", reach: "1,5m" }],
    description: "Goblinoide militarizado, menos caotico que goblins e mais perigoso em grupo organizado.",
    suggestedLevels: [1, 2, 3],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "black-bear",
    name: "Urso Negro",
    kind: "beast",
    size: "medium",
    family: "bear",
    role: "brute",
    biomeTags: ["floresta", "montanha", "caverna"],
    challengeRating: "1/2",
    xpValue: 100,
    armorClass: 11,
    hitPoints: 19,
    speed: "12m, escalar 9m",
    abilities: { strength: 15, agility: 10, constitution: 14, mind: 2, wisdom: 12, presence: 7 },
    senses: "olfato aguçado",
    traits: ["Territorial: ataca para expulsar invasores antes de perseguir ate a morte."],
    actions: [{ name: "Garras", attackBonus: 3, damageDie: "d6", damageDiceCount: 2, damageModifier: 2, damageType: "cortante", reach: "1,5m" }],
    description: "Animal forte e territorial, bom para encontros naturais que nao precisam ser malignos.",
    suggestedLevels: [1, 2],
    difficultyBand: ["standard"],
  },
  {
    id: "brown-bear",
    name: "Urso Pardo",
    kind: "beast",
    size: "large",
    family: "bear",
    role: "brute",
    biomeTags: ["floresta", "montanha", "caverna", "fronteira"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 11,
    hitPoints: 34,
    speed: "12m, escalar 9m",
    abilities: { strength: 19, agility: 10, constitution: 16, mind: 2, wisdom: 13, presence: 7 },
    senses: "olfato aguçado",
    traits: ["Carga brutal: pressiona o alvo mais proximo e pune quem se aproxima de filhotes ou comida."],
    actions: [{ name: "Garras", attackBonus: 5, damageDie: "d8", damageDiceCount: 2, damageModifier: 4, damageType: "cortante", reach: "1,5m" }],
    description: "Predador poderoso de baixo nivel, mais problema ambiental do que vilao consciente.",
    suggestedLevels: [2, 3],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "giant-snake",
    name: "Serpente Gigante",
    kind: "beast",
    size: "large",
    family: "snake",
    role: "controller",
    biomeTags: ["pantano", "floresta", "rio", "selva", "caverna"],
    challengeRating: "1/4",
    xpValue: 50,
    armorClass: 12,
    hitPoints: 13,
    speed: "9m, nadar 9m",
    abilities: { strength: 15, agility: 14, constitution: 12, mind: 2, wisdom: 10, presence: 3 },
    senses: "sentido de vibração",
    traits: ["Constricao: tenta prender e limitar movimento antes de morder."],
    actions: [{ name: "Mordida", attackBonus: 4, damageDie: "d6", damageDiceCount: 1, damageModifier: 2, damageType: "perfurante", reach: "1,5m" }],
    description: "Predador silencioso de matas e pantanos, bom para encontros de tensao e terreno dificil.",
    suggestedLevels: [1, 2],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "harpy",
    name: "Harpia",
    kind: "monstrosity",
    size: "medium",
    family: "harpy",
    role: "controller",
    biomeTags: ["penhasco", "costa", "ruina", "floresta", "montanha"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 11,
    hitPoints: 38,
    speed: "6m, voo 12m",
    abilities: { strength: 12, agility: 13, constitution: 12, mind: 7, wisdom: 10, presence: 13 },
    languages: "Comum",
    traits: ["Canção sedutora: tenta atrair presas para perigo antes do ataque."],
    actions: [{ name: "Garras", attackBonus: 3, damageDie: "d4", damageDiceCount: 2, damageModifier: 1, damageType: "cortante", reach: "1,5m" }],
    description: "Monstruosidade alada que mistura ameaça social, controle mental leve e perigo de queda.",
    suggestedLevels: [2, 3],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "animated-armor",
    name: "Armadura Animada",
    kind: "construct" as MonsterStatBlock["kind"],
    size: "medium",
    family: "construct",
    role: "soldier",
    biomeTags: ["castelo", "templo", "ruina", "masmorra", "mansao"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 18,
    hitPoints: 33,
    speed: "7,5m",
    abilities: { strength: 14, agility: 11, constitution: 13, mind: 1, wisdom: 3, presence: 1 },
    senses: "percepcao magica limitada",
    traits: ["Construto: imune a medo comum e negociacao simples.", "Guardiao: protege local, objeto ou porta."],
    actions: [{ name: "Pancada metalica", attackBonus: 4, damageDie: "d6", damageDiceCount: 1, damageModifier: 2, damageType: "concussao", reach: "1,5m" }],
    description: "Guardiao magico sem vontade propria, bom para ruinas, templos e tesouros protegidos.",
    suggestedLevels: [2, 3],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "imp",
    name: "Diabrete",
    kind: "fiend" as MonsterStatBlock["kind"],
    size: "small",
    family: "fiend",
    role: "lurker",
    biomeTags: ["templo", "cidade", "ruina", "infernal", "torre"],
    challengeRating: "1",
    xpValue: 200,
    armorClass: 13,
    hitPoints: 10,
    speed: "6m, voo 12m",
    abilities: { strength: 6, agility: 17, constitution: 13, mind: 11, wisdom: 12, presence: 14 },
    senses: "visao no escuro",
    languages: "Comum, Infernal",
    traits: ["Invisibilidade menor: prefere enganar, observar e ferir quando o alvo esta vulneravel."],
    actions: [{ name: "Ferrão", attackBonus: 5, damageDie: "d4", damageDiceCount: 1, damageModifier: 3, damageType: "perfurante", reach: "1,5m", notes: "Veneno pode impor consequencia narrativa." }],
    description: "Diabo pequeno e malicioso, melhor usado como espião, tentador ou assassino oportunista.",
    suggestedLevels: [2, 3],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "bandit-captain",
    name: "Capitao Bandido",
    kind: "humanoid",
    size: "medium",
    family: "criminal",
    role: "leader",
    biomeTags: ["cidade", "estrada", "porto", "acampamento", "taverna"],
    challengeRating: "2",
    xpValue: 450,
    armorClass: 15,
    hitPoints: 65,
    speed: "9m",
    abilities: { strength: 15, agility: 16, constitution: 14, mind: 14, wisdom: 11, presence: 14 },
    languages: "Comum",
    traits: ["Lideranca criminosa: usa refens, vantagem social e capangas antes de arriscar a propria vida."],
    actions: [{ name: "Cimitarra", attackBonus: 5, damageDie: "d6", damageDiceCount: 1, damageModifier: 3, damageType: "cortante", reach: "1,5m" }],
    description: "Vilao humano de baixo nivel, apropriado como chefe de arco curto ou rival recorrente.",
    suggestedLevels: [3, 4],
    difficultyBand: ["deadly", "standard"],
  },
  {
    id: "wight",
    name: "Inumano",
    kind: "undead",
    size: "medium",
    family: "wight",
    role: "leader",
    biomeTags: ["cripta", "cemiterio", "ruina", "templo", "campo de batalha"],
    challengeRating: "3",
    xpValue: 700,
    armorClass: 14,
    hitPoints: 45,
    speed: "9m",
    abilities: { strength: 15, agility: 14, constitution: 16, mind: 10, wisdom: 13, presence: 15 },
    senses: "visao no escuro",
    languages: "idiomas que conhecia em vida",
    traits: ["Drenar vida: feridas podem deixar marcas duradouras.", "Comando morto-vivo: pode liderar esqueletos e zumbis."],
    actions: [{ name: "Espada longa", attackBonus: 4, damageDie: "d8", damageDiceCount: 1, damageModifier: 2, damageType: "cortante", reach: "1,5m" }],
    description: "Morto-vivo consciente e odioso, bom como comandante de cripta ou consequencia de maldicao.",
    suggestedLevels: [4, 5],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "manticore",
    name: "Manticora",
    kind: "monstrosity",
    size: "large",
    family: "manticore",
    role: "artillery",
    biomeTags: ["montanha", "deserto", "ruina", "fronteira"],
    challengeRating: "3",
    xpValue: 700,
    armorClass: 14,
    hitPoints: 68,
    speed: "9m, voo 15m",
    abilities: { strength: 17, agility: 16, constitution: 17, mind: 7, wisdom: 12, presence: 8 },
    senses: "visao no escuro",
    languages: "Comum",
    traits: ["Ataque aereo: prefere voar fora do alcance e disparar espinhos.", "Crueldade inteligente: negocia se estiver em desvantagem."],
    actions: [{ name: "Espinho da cauda", attackBonus: 5, damageDie: "d8", damageDiceCount: 1, damageModifier: 3, damageType: "perfurante", range: "30/60m" }],
    description: "Monstruosidade alada cruel, excelente para encontros em terreno aberto e ameaça de longa distancia.",
    suggestedLevels: [4, 5],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "owlbear",
    name: "Ursocoruja",
    kind: "monstrosity",
    size: "large",
    family: "owlbear",
    role: "brute",
    biomeTags: ["floresta", "caverna", "montanha", "ruina"],
    challengeRating: "3",
    xpValue: 700,
    armorClass: 13,
    hitPoints: 59,
    speed: "12m",
    abilities: { strength: 20, agility: 12, constitution: 17, mind: 3, wisdom: 12, presence: 7 },
    senses: "olfato e visao aguçados",
    traits: ["Furia territorial: escolhe um alvo e tenta esmagar ate ele cair."],
    actions: [{ name: "Garras", attackBonus: 7, damageDie: "d8", damageDiceCount: 2, damageModifier: 5, damageType: "cortante", reach: "1,5m" }],
    description: "Predador monstruoso de florestas e cavernas, simples, memoravel e perigoso.",
    suggestedLevels: [4, 5],
    difficultyBand: ["standard", "deadly"],
  },
  {
    id: "gelatinous-cube",
    name: "Cubo Gelatinoso",
    kind: "monstrosity",
    size: "large",
    family: "ooze",
    role: "controller",
    biomeTags: ["masmorra", "esgoto", "ruina", "caverna"],
    challengeRating: "2",
    xpValue: 450,
    armorClass: 6,
    hitPoints: 84,
    speed: "4,5m",
    abilities: { strength: 14, agility: 3, constitution: 20, mind: 1, wisdom: 6, presence: 1 },
    senses: "sentido cego",
    traits: ["Transparente: facil de notar tarde demais.", "Engolir: ameaça prender quem fica no corredor."],
    actions: [{ name: "Pseudopode acido", attackBonus: 4, damageDie: "d6", damageDiceCount: 3, damageModifier: 0, damageType: "acido", reach: "1,5m" }],
    description: "Ameaça de masmorra que muda o combate por posicionamento, mais quebra-cabeca que duelo.",
    suggestedLevels: [3, 4],
    difficultyBand: ["story", "standard"],
  },
  {
    id: "gargoyle",
    name: "Gargula",
    kind: "elemental",
    size: "medium",
    family: "gargoyle",
    role: "lurker",
    biomeTags: ["templo", "castelo", "ruina", "cidade", "torre"],
    challengeRating: "2",
    xpValue: 450,
    armorClass: 15,
    hitPoints: 52,
    speed: "9m, voo 18m",
    abilities: { strength: 15, agility: 11, constitution: 16, mind: 6, wisdom: 11, presence: 7 },
    senses: "visao no escuro",
    traits: ["Aparencia falsa: parece estatua ate se mover.", "Pele de pedra: resiste a ferimentos comuns."],
    actions: [{ name: "Garras de pedra", attackBonus: 4, damageDie: "d6", damageDiceCount: 1, damageModifier: 2, damageType: "cortante", reach: "1,5m" }],
    description: "Guardiao alado de pedra, excelente para ruinas, telhados e templos antigos.",
    suggestedLevels: [3, 4],
    difficultyBand: ["standard", "deadly"],
  },
];

export const monsterCatalog: MonsterStatBlock[] = [...coreMonsterCatalog, ...expandedMonsterCatalog];

const difficultyScore: Record<EnemyDifficulty, number> = { story: 0, standard: 1, deadly: 2 };

const monsterThreat = (monster: MonsterStatBlock): number => Math.max(2, Math.round((monster.actions[0]?.attackBonus ?? 3) / 2));

export const selectMonsterEncounter = (
  playerCount: number,
  averageLevel: number,
  difficulty: EnemyDifficulty,
  intensity: BattleIntensity,
  sceneContext = "",
): EncounterMonster[] => {
  const groupSize = intensity === "high" ? (playerCount >= 3 ? 3 : 2) : intensity === "medium" ? (playerCount >= 3 ? 2 : 1) : 1;
  const sceneTags = inferSceneTags(sceneContext);
  const level = Math.max(1, Math.min(5, averageLevel));
  const levelCandidates = monsterCatalog
    .filter((monster) => monster.suggestedLevels.includes(level))
    .filter((monster) => monster.difficultyBand.includes(difficulty));
  const contextualCandidates = levelCandidates
    .filter((monster) => sceneTags.length === 0 || monsterTags(monster).some((tag) => sceneTags.includes(tag)));
  const candidates = (contextualCandidates.length > 0 ? contextualCandidates : levelCandidates)
    .filter((monster) => monster.suggestedLevels.includes(Math.max(1, Math.min(5, averageLevel))))
    .filter((monster) => monster.difficultyBand.includes(difficulty))
    .sort((a, b) => {
      const contextDelta = contextScore(b, sceneTags) - contextScore(a, sceneTags);
      if (contextDelta !== 0) return contextDelta;
      return Math.abs(difficultyScore[difficulty] - Math.max(...a.difficultyBand.map((band) => difficultyScore[band]))) - Math.abs(difficultyScore[difficulty] - Math.max(...b.difficultyBand.map((band) => difficultyScore[band])));
    });
  const fallback = monsterCatalog.find((monster) => monster.id === "goblin") ?? monsterCatalog[0];
  const topCandidates = candidates.slice(0, Math.min(4, candidates.length));
  const base = topCandidates.length > 0 ? topCandidates[Math.floor(Math.random() * topCandidates.length)] : fallback;
  const hpScale = intensity === "low" ? 0.9 : intensity === "high" ? 1.1 : 1;
  const variants = ["", "veterano", "ferido", "raivoso"];

  return Array.from({ length: groupSize }).map((_, index) => ({
    ...base,
    name: groupSize === 1 ? base.name : `${base.name} ${variants[index] || index + 1}`.trim(),
    hitPoints: Math.max(1, Math.round(base.hitPoints * hpScale / Math.max(1, groupSize > 1 ? 1.15 : 1))),
    xpValue: Math.max(10, Math.round(base.xpValue / Math.max(1, groupSize > 1 ? groupSize : 1))),
    threat: monsterThreat(base),
  }));
};

const normalizeTag = (value: string): string => value
  .normalize("NFD")
  .replace(/[\u0300-\u036f]/g, "")
  .toLowerCase();

const inferSceneTags = (sceneContext: string): string[] => {
  const normalized = normalizeTag(sceneContext);
  const tagMap: Array<[string, string[]]> = [
    ["floresta", ["floresta", "mata", "bosque", "selva"]],
    ["caverna", ["caverna", "gruta", "mina", "subterraneo"]],
    ["cripta", ["cripta", "cemiterio", "tumba", "catacumba", "sepultura", "mausoleu"]],
    ["templo", ["templo", "igreja", "capela", "santuario", "altar"]],
    ["cidade", ["cidade", "vila", "mercado", "praca", "guilda", "rua"]],
    ["taverna", ["taverna", "estalagem", "bar", "pousada"]],
    ["estrada", ["estrada", "trilha", "caminho", "carroca", "fronteira"]],
    ["pantano", ["pantano", "alagado", "brejo", "mangue"]],
    ["deserto", ["deserto", "duna", "areia"]],
    ["montanha", ["montanha", "penhasco", "rochedo", "desfiladeiro"]],
    ["esgoto", ["esgoto", "bueiro", "subsolo"]],
    ["porto", ["porto", "navio", "doca", "cais", "embarcacao"]],
    ["forte", ["forte", "fortaleza", "acampamento", "quartel", "militar"]],
  ];
  return tagMap
    .filter(([, words]) => words.some((word) => normalized.includes(word)))
    .map(([tag]) => tag);
};

const contextScore = (monster: MonsterStatBlock, sceneTags: string[]): number => {
  if (sceneTags.length === 0) return 0;
  const tags = monsterTags(monster);
  return sceneTags.filter((tag) => tags.includes(tag)).length;
};

const monsterTags = (monster: MonsterStatBlock): string[] => {
  const explicit = (monster.biomeTags ?? []).map(normalizeTag);
  if (explicit.length > 0) return explicit;
  const name = normalizeTag(`${monster.id} ${monster.name} ${monster.kind} ${monster.description}`);
  const inferred: string[] = [];
  if (monster.kind === "undead" || name.includes("esqueleto") || name.includes("zumbi") || name.includes("carnical")) inferred.push("cripta", "cemiterio", "templo", "ruina");
  if (monster.kind === "beast" || name.includes("lobo")) inferred.push("floresta", "estrada");
  if (monster.kind === "humanoid") inferred.push("cidade", "estrada", "acampamento", "ruina");
  if (monster.kind === "giant") inferred.push("montanha", "caverna", "fronteira", "floresta");
  if (monster.kind === "elemental") inferred.push("ruina", "templo", "caverna", "montanha");
  if (name.includes("goblin") || name.includes("bugbear")) inferred.push("floresta", "caverna", "ruina");
  if (name.includes("cultista")) inferred.push("templo", "cripta", "cidade");
  if (name.includes("bandido") || name.includes("bandit") || name.includes("capanga")) inferred.push("taverna", "cidade", "estrada", "porto");
  if (name.includes("guarda")) inferred.push("cidade", "forte", "acampamento", "estrada");
  if (name.includes("orc")) inferred.push("estrada", "fronteira", "acampamento", "floresta");
  return [...new Set(inferred)];
};
